###
GET http://localhost:3000/api/v1/

### 
POST http://localhost:3000/api/v1/admin/register
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### 
POST http://localhost:3000/api/v1/admin/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:3000/api/v1/admin/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTcwMTY2Nzk0NCwiZXhwIjoxNzAxNzU0MzQ0fQ.MZV-DLPnSRcGr1Em3xltssN4nISto_9J5GYuYCj3NSw

### dapatkan semua hotel
GET http://localhost:3000/api/v1/hotel

### dapatkan semua hotel
GET http://localhost:3000/api/v1/hotel?page=1&limit=10

### dapatkan hotel berdasarkan id
GET http://localhost:3000/api/v1/hotel/:id

### create hotel
POST http://localhost:3000/api/v1/hotel
Content-Type: application/json

{
    "name": "Hotel 1",
    "address": "Jl. Hotel 1",
    "phone": "08123456789",
    "email": ""
}

### update hotel
PUT http://localhost:3000/api/v1/hotel/:id

### delete hotel
DELETE http://localhost:3000/api/v1/hotel/:id

